export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  MERGE_SAME_CARD: "MERGE_SAME_CARD",
  MERGE_CARD_NOT_FOUND: "MERGE_CARD_NOT_FOUND",
  MERGE_ALIAS_AMBIGUOUS: "MERGE_ALIAS_AMBIGUOUS",
  MERGE_DUPLICATE_CONFLICT: "MERGE_DUPLICATE_CONFLICT",
  MERGE_LOCK_BUSY: "MERGE_LOCK_BUSY",
  MERGE_NOT_FAILED: "MERGE_NOT_FAILED",
  MERGE_ALREADY_REVERTED: "MERGE_ALREADY_REVERTED",
  MERGE_CHAIN_BLOCKED: "MERGE_CHAIN_BLOCKED",
  MERGE_STALE_CONFLICT: "MERGE_STALE_CONFLICT",
  MERGE_NOT_REVERSIBLE: "MERGE_NOT_REVERSIBLE",
  MERGE_REQUEST_NOT_FOUND: "MERGE_REQUEST_NOT_FOUND",
  SERVICE_ERROR: "SERVICE_ERROR",
  API_ERROR: "API_ERROR",
  CONTROLLER_ERROR: "CONTROLLER_ERROR"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
