export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  MERGE_SOURCE_TARGET_SAME: "MERGE_SOURCE_TARGET_SAME",
  MERGE_SYMBOL_NOT_FOUND: "MERGE_SYMBOL_NOT_FOUND",
  MERGE_CONFLICT: "MERGE_CONFLICT",
  MERGE_ALREADY_COMMITTED: "MERGE_ALREADY_COMMITTED",
  MERGE_NOT_FOUND: "MERGE_NOT_FOUND",
  MERGE_SNAPSHOT_MISSING: "MERGE_SNAPSHOT_MISSING",
  MERGE_NOT_ROLLBACKABLE: "MERGE_NOT_ROLLBACKABLE",
  MERGE_ROLLBACK_CONFLICT: "MERGE_ROLLBACK_CONFLICT",
  MERGE_ALREADY_ROLLED_BACK: "MERGE_ALREADY_ROLLED_BACK",
  MERGE_VERSION_MISMATCH: "MERGE_VERSION_MISMATCH"
} as const;
